Remove -no-opaque-pointers flag
denoland/chromium_build pull request #197
Opened 2022-06-08 16:16 UTC by cd-work

According to the upstream bug report, the flag should no longer be
necessary and it causes a failure on platforms where it is not
supported.

2022-06-19 00:05 UTC, avindra commented
:+1: openSUSE doesn't know what this flag is, breaking the build. Removing the flag fixes the build on SUSE platform.

2022-06-27 05:48 UTC, cd-work commented
Any feedback either way would be appreciated. Would just like a status update since this has been on hold for a while.

2022-08-25 18:01 UTC, avindra requested changes
Latest code works with clang14

2022-08-25 18:01 UTC, avindra commented on config/compiler/BUILD.gn
> -          clang_major_version >= 15) {
this change `clang_major_version >= 15)` satisfies my problem where I'm using clang 14. removed local patch and no error from the build.

2025-06-19 05:32 UTC, linrongbin16 commented on config/compiler/BUILD.gn
> -          clang_major_version >= 15) {
This PR could be closed, since in the latest production branch `20250609`, this code branch is already deleted.

See: https://github.com/denoland/chromium_build/blob/c9710dd40f8bd0f26350626fa185eadd3fb09b9c/config/compiler/BUILD.gn#L2097-L2119

Code logic:
```
config("default_warnings") => if (is_clang) => if (!is_nacl || is_nacl_saigo)
```

2025-06-30 15:12 UTC, closed without merging